// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android is not configured in firebase_options.dart. Use google-services.json instead.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not configured in firebase_options.dart. Use GoogleService-Info.plist instead.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not configured yet.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not configured yet.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6MKl4lYYbyE6Zmwn_ggig0PH4vkijt4',
    appId: '1:233368126864:web:7baf820306393359c5df15',
    messagingSenderId: '233368126864',
    projectId: 'mp-final-project-d753a',
    authDomain: 'mp-final-project-d753a.firebaseapp.com',
    storageBucket: 'mp-final-project-d753a.firebasestorage.app',
    measurementId: 'G-0LVP3VYDD2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_MACOS_MESSAGING_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    iosClientId: 'REPLACE_WITH_YOUR_MACOS_IOS_CLIENT_ID',
    iosBundleId: 'REPLACE_WITH_YOUR_MACOS_BUNDLE_ID',
  );
}
